# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fdcd05ba6deb844bda30451451f3a6f8a1da6fac859ff47ccd78c021ab10dd00aeaa9e5a6d77b37b09d9d38948cffae6f0505c39f5fb3de840bd76397327a0c

test:
  secret_key_base: b14900b1065c4001be625e665312df7937214899a21fe836cba82d8aee355e5910f7b6c6bfb7538093e0c405127638871f0e843157e38ac37930fa297e500317

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
